### PR TITLE
Closes #13 - adds top-center and bottom-center notifier position options

### LINKED ISSUE #13: 'bottom-center' position?
I was wondering how I might position notifications in a 'bottom-center' position?  This works well for my mobile-device browser users.

Right now I am using PNotify to provide this functionality (PNotify refers to this as the "bottom bar" style of stack which is set using the `stack: stack_bar_bottom` option and you can see a demo of it here:  http://sciactive.com/pnotify/#stacks), but I would like to use only Alertify.

PS:   Love this library!

### PR DESCRIPTION
**Pull request by christianklemp**
Also updates package.json to use needed grunt-rtlcss version (I wasn't able to get the `.ajs-` prefix addition working without explicitly downgrading the the changed-to version) and to use `grunt-postcss` with the `autoprefixer` plugin instead of the deprecated `grunt-autoprefixer` package that was no longer adding the vendor prefixes.

*Note: all whitespacing changes are due to my editor, Atom, performing clean up when I save files.

### CODE REVIEW

**Comment by MohammadYounes** [comment]
Thanks, I'll review this as soon as possible. However, this project has a commercial license and thus:

Do you consent that You provide Your Contributions on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied, including, without limitation, any warranties or conditions of TITLE, NON- INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE ?

**Comment by christianklemp-imt** [comment]
👍 I do

**Comment by MohammadYounes** [comment]
Thank you, But I believe you should consent using the same account used to issue the PR.

**Comment by christianklemp** [comment]
My bad! 👍 I do consent to the above statement.

**Comment by MohammadYounes** [comment]
Awesome... Thanks!

**Pull request merged**
