### PR TITLE
Add option for custom classes on notifier

### PR DESCRIPTION
**Pull request by FoxxMD**
This pull adds the option **messageClasses** to notifier. 

It adds classes specified in this option to the **ajs-message** `div` element allowing the ability customize the look/feel of the message element.

This pull also fixes some problems I encountered in building the project which were due to bugs in older packages. I updated them to the newest or recommended versions based on solutions in the issues linked in each commit.

### CODE REVIEW

**Comment by MohammadYounes** [comment]
Thanks! But you can already customize the message element by overriding `ajs-message` rule. Also you can use [`alertify.notify`](http://alertifyjs.com/notifier.html#notify) to create your own custom messages.

**Comment by MohammadYounes** [comment]
Partially merged in d0ffe8317dde56f04c11f08afd35af08b6036e4e and 895aaf62b7c728d0c594dd803babf436c15d1fac, I also update the docs to emphasize on how to [customize](http://alertifyjs.com/notifier.html#notify) the notification message.

Thanks.

**Comment by FoxxMD** [comment]
thanks!

**Comment by MohammadYounes** [comment]
@FoxxMD That's still [possible](http://codepen.io/anon/pen/BNyLBz) as the library only adds the prefix to the whole string:
```js
// it's also possible to omit the custom class by just adding a space ' ui positive message'
alertify.notify('custom positive message', 'custom ui positive message', 0);
```

**Comment by FoxxMD** [comment]
ah okay! thanks for clarifying

**Pull request closed without merging**
