### PR TITLE
Provided bower.json

### PR DESCRIPTION
**Pull request by fcamblor**
Provided bower.json file with main alertify js script
This will allow to autowire dependency in index.html using the `grunt-wiredep` plugin (and it will remove some warning when using `bower`)

### CODE REVIEW

**Comment by MohammadYounes** [comment]
Thanks, But I'm keeping this without bower (see #2, #14 and #15).

**Comment by fcamblor** [comment]
I don't really get it, you plan to rename the project name prior to providing bower support ?

Or you'll *never* provide such support ?

**Comment by MohammadYounes** [comment]
I'm waiting for the name AlertifyJS to become available, once it does! I'll definitely provide bower support.

**Comment by fcamblor** [comment]
Thanks for the precision

What are the drawbacks of using the existing `alertify-js` key prior to wait for `alertify` availability ?

You think it may be misleading for the community ? 
(regarding we already have `alertify`, `alertify.js`, `alertifyjs` and `alertify-js` in bower registry .. To my POV, seeing this, users can be aware they should be cautious when using the *right* package name)

**Comment by MohammadYounes** [comment]
It's a matter of preference, that's all! Does it help if I unregister the current bower package `alertify-js` so you can re-publish on your own?

**Comment by fcamblor** [comment]
Nope, already referenced my custom (4sh) repository in my `bower.json` file, no problem

Maybe you should track this issue (keeping the issue opened) because I looked at opened issues/PR before submitting my PR (didn't checked closed ones), and I think I won't be the only one requiring `bower` package definition :-)

**Comment by fcamblor** [comment]
FYI, I just updated my `bower.json` file to specify `require-js` `main` field override :
```
{
...
  "dependencies": {
    ...
    "alertify-js": "1.0.1"
  },
  "overrides": {
    "alertify-js": {
      "main": [
        "./build/css/alertify.css",
        "./build/css/themes/bootstrap.css",
        "./build/alertify.js"
      ]
    }
  },
}
```

Hope it can help folks while `bower` official support is not provided :)

**Comment by MohammadYounes** [comment]
Thanks for sharing :)

**Pull request closed without merging**
